config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  # Tell devise to use our registrations controller (to support first/last name for user registrations)
  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :users do
    resources :job_applications, only: [:show, :index]
  end

  resources :jobs, :job_applications

  get "/dashboard" => "jobs#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/sortable.rb
module Sortable

  module InstanceMethods
    def posting_date
      self.created_at.strftime("%b %d, %Y")
    end
  end

  module ClassMethods
    def all_sort_by_date
      all.order(created_at: "DESC" )
    end

    def order_and_paginated(params, pages)
      all_sort_by_date.page(params).per(pages)
    end
  end

end

app/models/job.rb
class Job < ApplicationRecord
  include Sortable::InstanceMethods
  extend Sortable::ClassMethods

  validates :title, :description, :company, :location, :company_id, presence: true
  belongs_to :user, :class_name => 'User', :foreign_key => 'company_id'
  has_many :job_applications, :dependent => :destroy
  has_many :applicants, :through => :job_applications, :class_name => 'User'
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  include Sortable::InstanceMethods
  extend Sortable::ClassMethods

  belongs_to :job
  belongs_to :applicant, :class_name => 'User', :foreign_key => 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Three roles are supported within the application...
  enum role: [:applicant, :employer, :admin]
  # ... but only allow signups for the first two roles
  validates :role, inclusion: { in: ['applicant', 'employer'],
    message: "unauthorized! Please select 'Applicant' or 'Employer' as your account type." }, on: :create

  # Require custom name fields on signup form and account edit form
  validates :first_name, :last_name, presence: true #, on: :create

  has_many :jobs, :foreign_key => 'company_id', :dependent => :destroy
  has_many :job_applications, :foreign_key => 'user_id'

  def set_default_role
    self.role ||= :applicant
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def user_not_authorized
    # flash[:alert] = "You are not authorized to perform this action"
    redirect_to root_path, alert: "You are not authorized to perform this action"
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, :except => [:index, :new, :create]

  def index
    @items_per_page = 5

    if params[:user_id] || current_user.applicant?
      @job_applications = current_user.job_applications.order_and_paginated(params[:page], @items_per_page)
    elsif current_user.admin?
      @job_applications = JobApplication.order_and_paginated(params[:page], @items_per_page)
    end
  end

  def new
    @job_application = JobApplication.new
    authorize @job_application
  end

  def create
    @job_application = JobApplication.find_by_user_id_and_job_id(params[:job_application][:user_id], params[:job_application][:job_id])

    if !@job_application.nil?
      redirect_to root_path, alert: "You already applied for this job"
    else
      @job_application = JobApplication.new(job_application_params)
      authorize @job_application
      if @job_application.save
        redirect_to root_path, alert: "Your application has been sent"
      else
        render_to new_job_application_path, alert: "Error: Your application could not be sent"
      end
    end
  end

  def show
    authorize @job_application
    @jobs = Job.all_sort_by_date.limit(10)
  end

  def edit
    authorize @job_application
  end

  def update
    authorize @job_application
  end

  def destroy
    authorize @job_application
    @job_application.destroy
    redirect_to root_path
  end

  private
  
  def set_job_application
    @job_application = JobApplication.find(params[:id])
  end

  def job_application_params
    params.require(:job_application).permit(:user_id, :job_id, :message)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index]

  def index
    @items_per_page = 5
    @jobs = Job.order_and_paginated(params[:page], @items_per_page)

    render :index 
    # respond_to_html_and_json(@jobs)
  end

  def new
    @job = Job.new
    authorize @job
  end

  def show
    @jobs = Job.all_sort_by_date.page.limit(5)
    render :show
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    authorize @job

    if @job.save
      redirect_to @job, alert: "Job opening created"
    else
      # Preserve validation error message array before render
      flash[:message] = @job.errors.full_messages
      render new_job_path, alert: "Error: Your job opening could not be created"
    end
  end

  def edit
    authorize @job
  end

  def update
    authorize @job
    @job.update(job_params)
    redirect_to @job, alert: "Job opening updated"
  end

  def dashboard
    if current_user.employer?
      @jobs = current_user.jobs.order_and_paginated(params[:page], 5)
    else
      redirect_to root_path, alert: "Unauthorized access"
    end
  end

  def destroy
    authorize @job
    @job.destroy
    redirect_to root_path, alert: "Job opening deleted"
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :company, :location, :company_id)
  end
end

app/controllers/registrations_controller.rb
# Extend Devise authentication default behavior to manage first_name and last_name fields 
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
  def current_job
    job = Job.find(params[:job_id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/job_applications/index.html.erb
<% if current_user.admin? %>
  <h1>Job applications</h1>
<% else %>
  <h1>My job applications</h1>
<% end %>

<% if @job_applications.empty? %>
  <% if current_user.admin? %>
    <h2>No job applications have been submitted</h2>
  <% else %>
    <h2>You have not yet applied to any jobs</h2>
  <% end %>

<% else %>
  <% @job_applications.each do |application| %>
    <div class="job-entry job-application">
      <p class="title"><%= application.job.title %></p>

      <% if current_user.admin? %>
        <p class="company"><%= application.job.company %></p>
        <p class="location"><%= application.job.location %></p>
        <p class="date">Applied: <%= application.posting_date %></p>
        <p class="applicant">Applicant: <%= application.applicant.first_name + " " + application.applicant.last_name + " <" + application.applicant.email + ">" %></p>

      <% else %>
        <p class="company"><%= application.job.company %></p>
        <p class="location"><%= application.job.location %></p>
        <p class="date">Applied: <%= application.posting_date %></p>
        <br>
        <p><%= button_to "View your application", user_job_application_path(current_user, application),  method: "get" %></p>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= paginate @job_applications %>

app/views/job_applications/new.html.erb
<h3>Apply for this job</h3>

<div class="job-entry">
  <p class="title"><%= current_job.title %></p>
  <p class="company"><%= current_job.company %></p>
  <p class="location"><%= current_job.location %></p>
  <p class="description"><%= truncate(current_job.description, length: 100) %></p>
</div>

<%= form_for(@job_application) do |f| %>
  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <%= f.hidden_field :job_id, :value => params[:job_id] %>

  <div class="field">
    <%= f.label :message, "Your message" %>
    <%= f.text_area :message, label: "Message"  %>
  </div>

  <br>

  <%= f.submit "Send Application" %>
<% end %>

app/views/job_applications/show.html.erb
<h3>My job applications: Details</h3>

<div class="job-entry job-application">
  <p class="title"><%= link_to @job_application.job.title, job_path(@job_application.job) %></p>
  <p class="company">Company: <%= @job_application.job.company %></p>
  <p class="location">Location: <%= @job_application.job.location %></p>
  <p class="date">Applied: <%= @job_application.posting_date %></p>
  <p class="description">Message: <%= @job_application.message %></p>
</div>

<%= button_to "Back to all job applications", job_applications_path, method: "get"  %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>

  <div class="field">
    <%= f.label :title, "Job title" %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :company, "Company" %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
  </div>

  <%= f.hidden_field :company_id, :value => current_user.id unless @job.company_id %>

  <br>
  
  <%= f.submit %>
  <p class="required">All fields are required</p>
<% end %>

app/views/jobs/dashboard.html.erb
<% if current_user && current_user.employer? %>
  <div id="dashboard">
    <h1>Employer Dashboard</h1>

    <% if @jobs.blank? %>
      <h2>No jobs currently available</h2>

    <% else %>
      <h2>Current job openings:</h2>

      <div class="job-listings">
      <% @jobs.each do |job| %>
        <div class="job-entry">
          <p class="title"><%= link_to job.title, job_path(job) %></p>
          <p class="company"><%= job.company %></p>
          <p class="location"><%= job.location %></p>
          <p class="date"><%= job.posting_date %></p>
          <p class="description"><%= truncate(job.description, length: 100) %></p>
        </div>

        <b>Applicants</b>

        <% if job.applicants.blank? %>
          <p>Nobody has applied to this job</p>

        <% else %>
          <ol class="applicants">
            <% job.applicants.each do |applicant| %>
              <li>
                <%= applicant.first_name + " " + applicant.last_name + " <" + applicant.email + ">" %><br>
                <% app_values = JobApplication.where(user_id: applicant.id, job_id: job.id).pluck(:created_at, :message)[0] %>
                <%= app_values[0].strftime("%b. %e, %Y | %l:%M %p") %><br>
                <%= app_values[1] %><br>
              </li>
            <% end %>
          </ol>
        <% end %>

        <br><br>

      <% end %>
      </div>

      <%= paginate @jobs %>

    <% end %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Edit job opening</h1>
<%= render 'form' %>

app/views/jobs/index.html.erb
<% if current_user %>
  <div class="tools-menu">
    <% if current_user.applicant? %>
      <h1>Applicant Tools</h1>
      <ul>
        <li><%= link_to "My job applications", user_job_applications_path(current_user) %></li>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>

    <% elsif current_user.employer? %>
      <h1>Employer Tools</h1>
      <ul>
        <li><%= link_to "Post a new job", new_job_path %></li>
        <li><%= link_to "My job openings", dashboard_path %></li>
        <li><%= link_to "My account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>

    <% elsif current_user.admin? %>
      <h1>Administrator Tools</h1>
      <ul>
        <li><%= link_to "Job applications", job_applications_path %></li>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>
    <% end %>
  </div>
<% end %>

  <% if @jobs.blank? %>
    <h2>No jobs currently available</h2>

  <% else %>
    <% if not current_user %>
      <div id="welcome_anonymous_visitor">
        <h1>Welcome!</h1>
        <h2>Sign up or log in for full access to all of our features</h2>
      </div>
    <% end %>

    <h2>Current job openings:</h2>
    <div class="job-listings">
      <% @jobs.each do |job| %>
        <div class="job-entry">
          <p class="title"><%= link_to job.title, job_path(job) %></p>
          <p class="company"><%= job.company %></p>
          <p class="location"><%= job.location %></p>
          <p class="date"><%= job.posting_date %></p>
          <p class="description"><%= truncate(job.description, length: 100) %></p>
        </div>
      <% end %>

      <%= paginate @jobs %>
    </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<h1>Post a new job opening</h1>
<%= render 'form' %>

app/views/jobs/show.html.erb
<div class="job-entry single">
  <p class="title"><%= @job.title %></p>
  <p class="company"><%= @job.company %></p>
  <p class="location"><%= @job.location %></p>
  <p class="date"><%= @job.posting_date %></p>
  <p class="description"><%= @job.description %></p>
</div>

<% if current_user.applicant? %>

  <% if current_user.job_applications.collect(&:job).include?(@job) %>
    <div class="already-applied">You applied to this job on 
      <%= current_user.job_applications.where(
        job_id: @job.id).pluck('created_at')[0].strftime("%b. %e, %Y at %l:%M %p") %></div>
  <% else %>
    <%= link_to "Apply", new_job_application_path(job_id: @job.id, user_id: current_user), method: "get", class: "btn" %>
  <% end %>

<% elsif policy(@job).update? %>
    <%= button_to "Edit", edit_job_path, method: "get" %>
    <%= button_to "Delete", job_path, method: "delete" %>
<% end %>

app/views/layouts/_alerts.html.erb
<% if not flash.empty? %>
  <div id="error_explanation">
    <ul>
      <% flash.each do |key, value| %>
        <% Array(value).each do |item| %>
          <li><%= item.html_safe %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<div id="logo"><%= link_to "Applicado", root_path %></div>
<div id="tagline">The job marketplace for applicants and employers</div>

<div class="menu">
  <% if !current_user %>
    <ul>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Log in", new_user_session_path %></li>
    </ul>

  <% else %>
    <div class="salutation">
      Welcome, <%= current_user.first_name %>
    </div>

    <% if current_user.employer? %>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Post a new job", new_job_path %></li>
        <li><%= link_to "My job openings", dashboard_path %></li>
        <li><%= link_to "My account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>

    <% else %>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li>
          <%= link_to "My job applications", job_applications_path unless current_user.admin? %>
          <%= link_to "Job applications", job_applications_path if current_user.admin? %>
        </li>
        <li><%= link_to "My Account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applicado: The job marketplace for applicants and employers</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <header>
        <%= render "layouts/menu" %>
      </header>

      <div class="main">
        <%= render "layouts/alerts" %>
        <%= yield %>
      </div>

      <footer>
        &copy; 2019 <b>Applicado</b>
      </footer>

    </div>
  </body>
</html>